version: "3.9"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mvc-project
    ports:
      - "3306:3306"
    networks:
      - mvc-project_default

networks:
  mvc-project_default:
    external: true
